[build]
# Static files from this folder will be served at the root of the site.
publish = "public"
[functions]
# Directory with serverless functions, including background
# functions, to deploy. This is relative to the base directory
# if one has been set, or the root directory if
# a base hasnâ€™t been set.
directory = "functions/"

# Specifies \`esbuild\` for functions bundling, esbuild is the default for TS
# node_bundler = "esbuild"

[functions."hello*"]
# Apply settings to any functions with a name beginning with "hello"